// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vbiriscv_mem_top.h for the primary calling header

#ifndef VERILATED_VBIRISCV_MEM_TOP_RISCV_CORE_H_
#define VERILATED_VBIRISCV_MEM_TOP_RISCV_CORE_H_  // guard

#include "verilated.h"
class Vbiriscv_mem_top_biriscv_csr__SB0;
class Vbiriscv_mem_top_biriscv_issue;


class Vbiriscv_mem_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vbiriscv_mem_top_riscv_core final : public VerilatedModule {
  public:
    // CELLS
    Vbiriscv_mem_top_biriscv_csr__SB0* u_csr;
    Vbiriscv_mem_top_biriscv_issue* u_issue;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk_i,0,0);
        VL_IN8(rst_i,0,0);
        VL_IN8(mem_d_accept_i,0,0);
        VL_IN8(mem_d_ack_i,0,0);
        VL_IN8(mem_d_error_i,0,0);
        VL_IN8(mem_i_accept_i,0,0);
        VL_IN8(mem_i_valid_i,0,0);
        VL_IN8(mem_i_error_i,0,0);
        VL_IN8(intr_i,0,0);
        VL_OUT8(mem_d_rd_o,0,0);
        VL_OUT8(mem_d_wr_o,3,0);
        VL_OUT8(mem_d_cacheable_o,0,0);
        VL_OUT8(mem_d_invalidate_o,0,0);
        VL_OUT8(mem_d_writeback_o,0,0);
        VL_OUT8(mem_d_flush_o,0,0);
        VL_OUT8(mem_i_rd_o,0,0);
        VL_OUT8(mem_i_flush_o,0,0);
        VL_OUT8(mem_i_invalidate_o,0,0);
        CData/*0:0*/ mmu_lsu_writeback_w;
        CData/*4:0*/ csr_opcode_rd_idx_w;
        CData/*4:0*/ mul_opcode_rd_idx_w;
        CData/*0:0*/ fetch1_instr_csr_w;
        CData/*0:0*/ branch_d_exec1_request_w;
        CData/*0:0*/ mmu_flush_w;
        CData/*1:0*/ fetch_in_priv_w;
        CData/*0:0*/ csr_opcode_valid_w;
        CData/*0:0*/ branch_csr_request_w;
        CData/*0:0*/ mmu_lsu_error_w;
        CData/*0:0*/ branch_exec0_is_call_w;
        CData/*0:0*/ mul_opcode_valid_w;
        CData/*0:0*/ branch_exec0_request_w;
        CData/*0:0*/ mmu_mxr_w;
        CData/*0:0*/ mmu_ifetch_valid_w;
        CData/*0:0*/ csr_opcode_invalid_w;
        CData/*5:0*/ csr_writeback_exception_w;
        CData/*0:0*/ branch_exec1_is_call_w;
        CData/*0:0*/ branch_exec1_is_not_taken_w;
        CData/*1:0*/ branch_d_exec0_priv_w;
        CData/*0:0*/ branch_exec1_is_taken_w;
        CData/*4:0*/ opcode1_rd_idx_w;
        CData/*0:0*/ fetch1_instr_invalid_w;
        CData/*3:0*/ mmu_lsu_wr_w;
        CData/*0:0*/ fetch_in_fault_w;
        CData/*0:0*/ fetch0_instr_rd_valid_w;
        CData/*0:0*/ branch_request_w;
        CData/*0:0*/ mmu_lsu_ack_w;
        CData/*0:0*/ writeback_mem_valid_w;
        CData/*5:0*/ csr_result_e1_exception_w;
        CData/*0:0*/ fetch0_instr_div_w;
        CData/*0:0*/ fetch0_fault_fetch_w;
        CData/*0:0*/ fetch1_fault_page_w;
        CData/*0:0*/ fetch1_instr_div_w;
        CData/*4:0*/ mul_opcode_ra_idx_w;
        CData/*4:0*/ csr_opcode_rb_idx_w;
        CData/*0:0*/ lsu_stall_w;
        CData/*0:0*/ branch_info_is_not_taken_w;
        CData/*4:0*/ opcode0_ra_idx_w;
        CData/*0:0*/ branch_info_is_taken_w;
        CData/*0:0*/ branch_info_is_ret_w;
        CData/*0:0*/ branch_exec0_is_taken_w;
        CData/*0:0*/ fetch1_instr_exec_w;
        CData/*0:0*/ fetch0_instr_exec_w;
        CData/*0:0*/ exec1_hold_w;
        CData/*0:0*/ exec0_opcode_valid_w;
    };
    struct {
        CData/*0:0*/ branch_info_is_jmp_w;
        CData/*0:0*/ fetch1_instr_lsu_w;
        CData/*0:0*/ branch_exec1_request_w;
        CData/*0:0*/ lsu_opcode_invalid_w;
        CData/*0:0*/ mul_hold_w;
        CData/*0:0*/ mmu_ifetch_accept_w;
        CData/*0:0*/ branch_exec1_is_jmp_w;
        CData/*0:0*/ mmu_ifetch_invalidate_w;
        CData/*1:0*/ branch_csr_priv_w;
        CData/*0:0*/ mmu_lsu_rd_w;
        CData/*0:0*/ fetch0_instr_mul_w;
        CData/*0:0*/ fetch0_accept_w;
        CData/*1:0*/ branch_priv_w;
        CData/*0:0*/ div_opcode_valid_w;
        CData/*0:0*/ fetch0_instr_lsu_w;
        CData/*0:0*/ interrupt_inhibit_w;
        CData/*0:0*/ mmu_ifetch_error_w;
        CData/*0:0*/ fetch0_instr_csr_w;
        CData/*5:0*/ writeback_mem_exception_w;
        CData/*0:0*/ fetch1_instr_branch_w;
        CData/*0:0*/ fetch0_valid_w;
        CData/*0:0*/ csr_result_e1_write_w;
        CData/*1:0*/ branch_d_exec1_priv_w;
        CData/*0:0*/ branch_exec0_is_not_taken_w;
        CData/*0:0*/ branch_exec1_is_ret_w;
        CData/*0:0*/ writeback_div_valid_w;
        CData/*4:0*/ mul_opcode_rb_idx_w;
        CData/*0:0*/ mmu_ifetch_rd_w;
        CData/*0:0*/ fetch0_fault_page_w;
        CData/*0:0*/ mmu_ifetch_flush_w;
        CData/*4:0*/ lsu_opcode_rd_idx_w;
        CData/*0:0*/ mmu_load_fault_w;
        CData/*4:0*/ opcode1_ra_idx_w;
        CData/*0:0*/ mmu_lsu_invalidate_w;
        CData/*4:0*/ csr_opcode_ra_idx_w;
        CData/*0:0*/ ifence_w;
        CData/*0:0*/ exec1_opcode_valid_w;
        CData/*0:0*/ branch_exec0_is_jmp_w;
        CData/*0:0*/ fetch1_accept_w;
        CData/*0:0*/ csr_writeback_write_w;
        CData/*0:0*/ take_interrupt_w;
        CData/*4:0*/ opcode1_rb_idx_w;
        CData/*0:0*/ fetch0_instr_invalid_w;
        CData/*0:0*/ fetch1_fault_fetch_w;
        CData/*0:0*/ fetch1_valid_w;
        CData/*0:0*/ mmu_lsu_cacheable_w;
        CData/*0:0*/ branch_d_exec0_request_w;
        CData/*0:0*/ opcode1_invalid_w;
        CData/*0:0*/ exec0_hold_w;
        CData/*4:0*/ opcode0_rb_idx_w;
        CData/*0:0*/ opcode0_invalid_w;
        CData/*0:0*/ lsu_opcode_valid_w;
        CData/*0:0*/ branch_info_request_w;
        CData/*1:0*/ mmu_priv_d_w;
        CData/*0:0*/ fetch0_instr_branch_w;
        CData/*0:0*/ mul_opcode_invalid_w;
        CData/*0:0*/ branch_exec0_is_ret_w;
        CData/*0:0*/ mmu_lsu_flush_w;
        CData/*4:0*/ lsu_opcode_rb_idx_w;
        CData/*0:0*/ mmu_lsu_accept_w;
        CData/*0:0*/ fetch1_instr_rd_valid_w;
        CData/*0:0*/ mmu_sum_w;
        CData/*0:0*/ branch_info_is_call_w;
        CData/*4:0*/ opcode0_rd_idx_w;
    };
    struct {
        CData/*4:0*/ lsu_opcode_ra_idx_w;
        CData/*0:0*/ fetch1_instr_mul_w;
        CData/*0:0*/ mmu_store_fault_w;
        CData/*0:0*/ u_frontend__DOT__clk_i;
        CData/*0:0*/ u_frontend__DOT__rst_i;
        CData/*0:0*/ u_frontend__DOT__icache_accept_i;
        CData/*0:0*/ u_frontend__DOT__icache_valid_i;
        CData/*0:0*/ u_frontend__DOT__icache_error_i;
        CData/*0:0*/ u_frontend__DOT__icache_page_fault_i;
        CData/*0:0*/ u_frontend__DOT__fetch0_accept_i;
        CData/*0:0*/ u_frontend__DOT__fetch1_accept_i;
        CData/*0:0*/ u_frontend__DOT__fetch_invalidate_i;
        CData/*0:0*/ u_frontend__DOT__branch_request_i;
        CData/*1:0*/ u_frontend__DOT__branch_priv_i;
        CData/*0:0*/ u_frontend__DOT__branch_info_request_i;
        CData/*0:0*/ u_frontend__DOT__branch_info_is_taken_i;
        CData/*0:0*/ u_frontend__DOT__branch_info_is_not_taken_i;
        CData/*0:0*/ u_frontend__DOT__branch_info_is_call_i;
        CData/*0:0*/ u_frontend__DOT__branch_info_is_ret_i;
        CData/*0:0*/ u_frontend__DOT__branch_info_is_jmp_i;
        CData/*0:0*/ u_frontend__DOT__icache_rd_o;
        CData/*0:0*/ u_frontend__DOT__icache_flush_o;
        CData/*0:0*/ u_frontend__DOT__icache_invalidate_o;
        CData/*1:0*/ u_frontend__DOT__icache_priv_o;
        CData/*0:0*/ u_frontend__DOT__fetch0_valid_o;
        CData/*0:0*/ u_frontend__DOT__fetch0_fault_fetch_o;
        CData/*0:0*/ u_frontend__DOT__fetch0_fault_page_o;
        CData/*0:0*/ u_frontend__DOT__fetch0_instr_exec_o;
        CData/*0:0*/ u_frontend__DOT__fetch0_instr_lsu_o;
        CData/*0:0*/ u_frontend__DOT__fetch0_instr_branch_o;
        CData/*0:0*/ u_frontend__DOT__fetch0_instr_mul_o;
        CData/*0:0*/ u_frontend__DOT__fetch0_instr_div_o;
        CData/*0:0*/ u_frontend__DOT__fetch0_instr_csr_o;
        CData/*0:0*/ u_frontend__DOT__fetch0_instr_rd_valid_o;
        CData/*0:0*/ u_frontend__DOT__fetch0_instr_invalid_o;
        CData/*0:0*/ u_frontend__DOT__fetch1_valid_o;
        CData/*0:0*/ u_frontend__DOT__fetch1_fault_fetch_o;
        CData/*0:0*/ u_frontend__DOT__fetch1_fault_page_o;
        CData/*0:0*/ u_frontend__DOT__fetch1_instr_exec_o;
        CData/*0:0*/ u_frontend__DOT__fetch1_instr_lsu_o;
        CData/*0:0*/ u_frontend__DOT__fetch1_instr_branch_o;
        CData/*0:0*/ u_frontend__DOT__fetch1_instr_mul_o;
        CData/*0:0*/ u_frontend__DOT__fetch1_instr_div_o;
        CData/*0:0*/ u_frontend__DOT__fetch1_instr_csr_o;
        CData/*0:0*/ u_frontend__DOT__fetch1_instr_rd_valid_o;
        CData/*0:0*/ u_frontend__DOT__fetch1_instr_invalid_o;
        CData/*0:0*/ u_frontend__DOT__fetch_valid_w;
        CData/*0:0*/ u_frontend__DOT__fetch_fault_page_w;
        CData/*1:0*/ u_frontend__DOT__next_taken_f_w;
        CData/*0:0*/ u_frontend__DOT__fetch_accept_w;
        CData/*1:0*/ u_frontend__DOT__fetch_pred_branch_w;
        CData/*0:0*/ u_frontend__DOT__fetch_fault_fetch_w;
        CData/*0:0*/ u_frontend__DOT__fetch_pc_accept_w;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__clk_i;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__rst_i;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__invalidate_i;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__branch_request_i;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__branch_is_taken_i;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__branch_is_not_taken_i;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__branch_is_call_i;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__branch_is_ret_i;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__branch_is_jmp_i;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__pc_accept_i;
        CData/*1:0*/ u_frontend__DOT__u_npc__DOT__next_taken_f_o;
    };
    struct {
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__pred_taken_w;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__pred_ntaken_w;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_valid_w;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_upper_w;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_is_call_w;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_is_ret_w;
        CData/*2:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__ras_index_real_q;
        CData/*2:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__ras_index_real_r;
        CData/*2:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__ras_index_q;
        CData/*2:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__ras_index_r;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__ras_call_pred_w;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__ras_ret_pred_w;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__bht_predict_taken_w;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_valid_r;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_upper_r;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_is_call_r;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_is_ret_r;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_is_jmp_r;
        CData/*4:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_entry_r;
        CData/*4:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_wr_entry_r;
        CData/*4:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_wr_alloc_w;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_hit_r;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_miss_r;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT____VdfgRegularize_hbaeca962_0_0;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__u_lru__DOT__clk_i;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__u_lru__DOT__rst_i;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__u_lru__DOT__hit_i;
        CData/*4:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__u_lru__DOT__hit_entry_i;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__u_lru__DOT__alloc_i;
        CData/*4:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__u_lru__DOT__alloc_entry_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__clk_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__rst_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_in_valid_i;
        CData/*1:0*/ u_frontend__DOT__u_decode__DOT__fetch_in_pred_branch_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_in_fault_fetch_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_in_fault_page_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out0_accept_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out1_accept_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__branch_request_i;
        CData/*1:0*/ u_frontend__DOT__u_decode__DOT__branch_priv_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_in_accept_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out0_valid_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out0_fault_fetch_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out0_fault_page_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out0_instr_exec_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out0_instr_lsu_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out0_instr_branch_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out0_instr_mul_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out0_instr_div_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out0_instr_csr_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out0_instr_rd_valid_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out0_instr_invalid_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out1_valid_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out1_fault_fetch_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out1_fault_page_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out1_instr_exec_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out1_instr_lsu_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out1_instr_branch_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out1_instr_mul_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out1_instr_div_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out1_instr_csr_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out1_instr_rd_valid_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__fetch_out1_instr_invalid_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__enable_muldiv_w;
    };
    struct {
        CData/*1:0*/ u_frontend__DOT__u_decode__DOT____Vcellinp__genblk1__DOT__u_fifo__info0_in_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__clk_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__rst_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__flush_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__push_i;
        CData/*1:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__pred_in_i;
        CData/*1:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__info0_in_i;
        CData/*1:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__info1_in_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__accept_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__valid0_o;
        CData/*1:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__info0_out_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__pop0_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__valid1_o;
        CData/*1:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__info1_out_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__pop1_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__rd_ptr_q;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__wr_ptr_q;
        CData/*1:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__count_q;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__push_w;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__pop1_w;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__pop2_w;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__pop_complete_w;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT__valid_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT__fetch_fault_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT__enable_muldiv_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT__invalid_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT__exec_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT__lsu_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT__branch_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT__mul_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT__div_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT__csr_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT__rd_valid_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT__invalid_w;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT__valid_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT__fetch_fault_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT__enable_muldiv_i;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT__invalid_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT__exec_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT__lsu_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT__branch_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT__mul_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT__div_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT__csr_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT__rd_valid_o;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT__invalid_w;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__clk_i;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__rst_i;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__fetch_accept_i;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__icache_accept_i;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__icache_valid_i;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__icache_error_i;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__icache_page_fault_i;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__fetch_invalidate_i;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__branch_request_i;
        CData/*1:0*/ u_frontend__DOT__u_fetch__DOT__branch_priv_i;
        CData/*1:0*/ u_frontend__DOT__u_fetch__DOT__next_taken_f_i;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__fetch_valid_o;
        CData/*1:0*/ u_frontend__DOT__u_fetch__DOT__fetch_pred_branch_o;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__fetch_fault_fetch_o;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__fetch_fault_page_o;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__icache_rd_o;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__icache_flush_o;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__icache_invalidate_o;
    };
    struct {
        CData/*1:0*/ u_frontend__DOT__u_fetch__DOT__icache_priv_o;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__pc_accept_o;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__active_q;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__icache_busy_w;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__stall_w;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__branch_q;
        CData/*1:0*/ u_frontend__DOT__u_fetch__DOT__branch_priv_q;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__branch_w;
        CData/*1:0*/ u_frontend__DOT__u_fetch__DOT__branch_priv_w;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__stall_q;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__icache_fetch_q;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__icache_invalidate_q;
        CData/*1:0*/ u_frontend__DOT__u_fetch__DOT__pred_d_q;
        CData/*1:0*/ u_frontend__DOT__u_fetch__DOT__icache_priv_w;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__fetch_resp_drop_w;
        CData/*0:0*/ u_frontend__DOT__u_fetch__DOT__skid_valid_q;
        CData/*0:0*/ u_mmu__DOT__clk_i;
        CData/*0:0*/ u_mmu__DOT__rst_i;
        CData/*1:0*/ u_mmu__DOT__priv_d_i;
        CData/*0:0*/ u_mmu__DOT__sum_i;
        CData/*0:0*/ u_mmu__DOT__mxr_i;
        CData/*0:0*/ u_mmu__DOT__flush_i;
        CData/*0:0*/ u_mmu__DOT__fetch_in_rd_i;
        CData/*0:0*/ u_mmu__DOT__fetch_in_flush_i;
        CData/*0:0*/ u_mmu__DOT__fetch_in_invalidate_i;
        CData/*1:0*/ u_mmu__DOT__fetch_in_priv_i;
        CData/*0:0*/ u_mmu__DOT__fetch_out_accept_i;
        CData/*0:0*/ u_mmu__DOT__fetch_out_valid_i;
        CData/*0:0*/ u_mmu__DOT__fetch_out_error_i;
        CData/*0:0*/ u_mmu__DOT__lsu_in_rd_i;
        CData/*3:0*/ u_mmu__DOT__lsu_in_wr_i;
        CData/*0:0*/ u_mmu__DOT__lsu_in_cacheable_i;
        CData/*0:0*/ u_mmu__DOT__lsu_in_invalidate_i;
        CData/*0:0*/ u_mmu__DOT__lsu_in_writeback_i;
        CData/*0:0*/ u_mmu__DOT__lsu_in_flush_i;
        CData/*0:0*/ u_mmu__DOT__lsu_out_accept_i;
        CData/*0:0*/ u_mmu__DOT__lsu_out_ack_i;
        CData/*0:0*/ u_mmu__DOT__lsu_out_error_i;
        CData/*0:0*/ u_mmu__DOT__fetch_in_accept_o;
        CData/*0:0*/ u_mmu__DOT__fetch_in_valid_o;
        CData/*0:0*/ u_mmu__DOT__fetch_in_error_o;
        CData/*0:0*/ u_mmu__DOT__fetch_out_rd_o;
        CData/*0:0*/ u_mmu__DOT__fetch_out_flush_o;
        CData/*0:0*/ u_mmu__DOT__fetch_out_invalidate_o;
        CData/*0:0*/ u_mmu__DOT__fetch_in_fault_o;
        CData/*0:0*/ u_mmu__DOT__lsu_in_accept_o;
        CData/*0:0*/ u_mmu__DOT__lsu_in_ack_o;
        CData/*0:0*/ u_mmu__DOT__lsu_in_error_o;
        CData/*0:0*/ u_mmu__DOT__lsu_out_rd_o;
        CData/*3:0*/ u_mmu__DOT__lsu_out_wr_o;
        CData/*0:0*/ u_mmu__DOT__lsu_out_cacheable_o;
        CData/*0:0*/ u_mmu__DOT__lsu_out_invalidate_o;
        CData/*0:0*/ u_mmu__DOT__lsu_out_writeback_o;
        CData/*0:0*/ u_mmu__DOT__lsu_out_flush_o;
        CData/*0:0*/ u_mmu__DOT__lsu_in_load_fault_o;
        CData/*0:0*/ u_mmu__DOT__lsu_in_store_fault_o;
        CData/*0:0*/ u_lsu__DOT__clk_i;
        CData/*0:0*/ u_lsu__DOT__rst_i;
        CData/*0:0*/ u_lsu__DOT__opcode_valid_i;
        CData/*0:0*/ u_lsu__DOT__opcode_invalid_i;
        CData/*4:0*/ u_lsu__DOT__opcode_rd_idx_i;
        CData/*4:0*/ u_lsu__DOT__opcode_ra_idx_i;
        CData/*4:0*/ u_lsu__DOT__opcode_rb_idx_i;
        CData/*0:0*/ u_lsu__DOT__mem_accept_i;
    };
    struct {
        CData/*0:0*/ u_lsu__DOT__mem_ack_i;
        CData/*0:0*/ u_lsu__DOT__mem_error_i;
        CData/*0:0*/ u_lsu__DOT__mem_load_fault_i;
        CData/*0:0*/ u_lsu__DOT__mem_store_fault_i;
        CData/*0:0*/ u_lsu__DOT__mem_rd_o;
        CData/*3:0*/ u_lsu__DOT__mem_wr_o;
        CData/*0:0*/ u_lsu__DOT__mem_cacheable_o;
        CData/*0:0*/ u_lsu__DOT__mem_invalidate_o;
        CData/*0:0*/ u_lsu__DOT__mem_writeback_o;
        CData/*0:0*/ u_lsu__DOT__mem_flush_o;
        CData/*0:0*/ u_lsu__DOT__writeback_valid_o;
        CData/*5:0*/ u_lsu__DOT__writeback_exception_o;
        CData/*0:0*/ u_lsu__DOT__stall_o;
        CData/*0:0*/ u_lsu__DOT__mem_rd_q;
        CData/*3:0*/ u_lsu__DOT__mem_wr_q;
        CData/*0:0*/ u_lsu__DOT__mem_cacheable_q;
        CData/*0:0*/ u_lsu__DOT__mem_invalidate_q;
        CData/*0:0*/ u_lsu__DOT__mem_writeback_q;
        CData/*0:0*/ u_lsu__DOT__mem_flush_q;
        CData/*0:0*/ u_lsu__DOT__mem_unaligned_e1_q;
        CData/*0:0*/ u_lsu__DOT__mem_unaligned_e2_q;
        CData/*0:0*/ u_lsu__DOT__mem_load_q;
        CData/*0:0*/ u_lsu__DOT__mem_xb_q;
        CData/*0:0*/ u_lsu__DOT__mem_xh_q;
        CData/*0:0*/ u_lsu__DOT__mem_ls_q;
        CData/*0:0*/ u_lsu__DOT__pending_lsu_e2_q;
        CData/*0:0*/ u_lsu__DOT__issue_lsu_e1_w;
        CData/*0:0*/ u_lsu__DOT__complete_ok_e2_w;
        CData/*0:0*/ u_lsu__DOT__complete_err_e2_w;
        CData/*0:0*/ u_lsu__DOT__delay_lsu_e2_w;
        CData/*0:0*/ u_lsu__DOT__load_inst_w;
        CData/*0:0*/ u_lsu__DOT__load_signed_inst_w;
        CData/*0:0*/ u_lsu__DOT__store_inst_w;
        CData/*0:0*/ u_lsu__DOT__req_lb_w;
        CData/*0:0*/ u_lsu__DOT__req_lh_w;
        CData/*0:0*/ u_lsu__DOT__req_lw_w;
        CData/*0:0*/ u_lsu__DOT__req_sb_w;
        CData/*0:0*/ u_lsu__DOT__req_sh_w;
        CData/*0:0*/ u_lsu__DOT__req_sw_w;
        CData/*0:0*/ u_lsu__DOT__req_sw_lw_w;
        CData/*0:0*/ u_lsu__DOT__req_sh_lh_w;
        CData/*0:0*/ u_lsu__DOT__mem_unaligned_r;
        CData/*0:0*/ u_lsu__DOT__mem_rd_r;
        CData/*3:0*/ u_lsu__DOT__mem_wr_r;
        CData/*0:0*/ u_lsu__DOT__dcache_flush_w;
        CData/*0:0*/ u_lsu__DOT__dcache_writeback_w;
        CData/*0:0*/ u_lsu__DOT__dcache_invalidate_w;
        CData/*0:0*/ u_lsu__DOT__resp_load_w;
        CData/*0:0*/ u_lsu__DOT__resp_byte_w;
        CData/*0:0*/ u_lsu__DOT__resp_half_w;
        CData/*0:0*/ u_lsu__DOT__resp_signed_w;
        CData/*0:0*/ u_lsu__DOT____Vcellinp__u_lsu_request__push_i;
        CData/*1:0*/ u_lsu__DOT__addr_lsb_r;
        CData/*0:0*/ u_lsu__DOT__load_byte_r;
        CData/*0:0*/ u_lsu__DOT__load_half_r;
        CData/*0:0*/ u_lsu__DOT__load_signed_r;
        CData/*0:0*/ u_lsu__DOT__fault_load_align_w;
        CData/*0:0*/ u_lsu__DOT__fault_store_align_w;
        CData/*0:0*/ u_lsu__DOT__fault_load_bus_w;
        CData/*0:0*/ u_lsu__DOT__fault_store_bus_w;
        CData/*0:0*/ u_lsu__DOT__fault_load_page_w;
        CData/*0:0*/ u_lsu__DOT__fault_store_page_w;
        CData/*0:0*/ u_lsu__DOT__u_lsu_request__DOT__clk_i;
        CData/*0:0*/ u_lsu__DOT__u_lsu_request__DOT__rst_i;
    };
    struct {
        CData/*0:0*/ u_lsu__DOT__u_lsu_request__DOT__push_i;
        CData/*0:0*/ u_lsu__DOT__u_lsu_request__DOT__pop_i;
        CData/*0:0*/ u_lsu__DOT__u_lsu_request__DOT__accept_o;
        CData/*0:0*/ u_lsu__DOT__u_lsu_request__DOT__valid_o;
        CData/*0:0*/ u_lsu__DOT__u_lsu_request__DOT__rd_ptr_q;
        CData/*0:0*/ u_lsu__DOT__u_lsu_request__DOT__wr_ptr_q;
        CData/*1:0*/ u_lsu__DOT__u_lsu_request__DOT__count_q;
        CData/*0:0*/ u_mul__DOT__clk_i;
        CData/*0:0*/ u_mul__DOT__rst_i;
        CData/*0:0*/ u_mul__DOT__opcode_valid_i;
        CData/*0:0*/ u_mul__DOT__opcode_invalid_i;
        CData/*4:0*/ u_mul__DOT__opcode_rd_idx_i;
        CData/*4:0*/ u_mul__DOT__opcode_ra_idx_i;
        CData/*4:0*/ u_mul__DOT__opcode_rb_idx_i;
        CData/*0:0*/ u_mul__DOT__hold_i;
        CData/*0:0*/ u_mul__DOT__mulhi_sel_e1_q;
        CData/*0:0*/ u_mul__DOT__mult_inst_w;
        CData/*0:0*/ u_div__DOT__clk_i;
        CData/*0:0*/ u_div__DOT__rst_i;
        CData/*0:0*/ u_div__DOT__opcode_valid_i;
        CData/*0:0*/ u_div__DOT__opcode_invalid_i;
        CData/*4:0*/ u_div__DOT__opcode_rd_idx_i;
        CData/*4:0*/ u_div__DOT__opcode_ra_idx_i;
        CData/*4:0*/ u_div__DOT__opcode_rb_idx_i;
        CData/*0:0*/ u_div__DOT__writeback_valid_o;
        CData/*0:0*/ u_div__DOT__valid_q;
        CData/*0:0*/ u_div__DOT__inst_div_w;
        CData/*0:0*/ u_div__DOT__inst_divu_w;
        CData/*0:0*/ u_div__DOT__inst_rem_w;
        CData/*0:0*/ u_div__DOT__inst_remu_w;
        CData/*0:0*/ u_div__DOT__div_rem_inst_w;
        CData/*0:0*/ u_div__DOT__signed_operation_w;
        CData/*0:0*/ u_div__DOT__div_operation_w;
        CData/*0:0*/ u_div__DOT__div_inst_q;
        CData/*0:0*/ u_div__DOT__div_busy_q;
        CData/*0:0*/ u_div__DOT__invert_res_q;
        CData/*0:0*/ u_div__DOT__last_div_q;
        CData/*0:0*/ u_div__DOT__last_divu_q;
        CData/*0:0*/ u_div__DOT__last_rem_q;
        CData/*0:0*/ u_div__DOT__last_remu_q;
        CData/*0:0*/ u_div__DOT__div_start_w;
        CData/*0:0*/ u_div__DOT__div_complete_w;
        CData/*0:0*/ u_exec0__DOT__clk_i;
        CData/*0:0*/ u_exec0__DOT__rst_i;
        CData/*0:0*/ u_exec0__DOT__opcode_valid_i;
        CData/*0:0*/ u_exec0__DOT__opcode_invalid_i;
        CData/*4:0*/ u_exec0__DOT__opcode_rd_idx_i;
        CData/*4:0*/ u_exec0__DOT__opcode_ra_idx_i;
        CData/*4:0*/ u_exec0__DOT__opcode_rb_idx_i;
        CData/*0:0*/ u_exec0__DOT__hold_i;
        CData/*0:0*/ u_exec0__DOT__branch_request_o;
        CData/*0:0*/ u_exec0__DOT__branch_is_taken_o;
        CData/*0:0*/ u_exec0__DOT__branch_is_not_taken_o;
        CData/*0:0*/ u_exec0__DOT__branch_is_call_o;
        CData/*0:0*/ u_exec0__DOT__branch_is_ret_o;
        CData/*0:0*/ u_exec0__DOT__branch_is_jmp_o;
        CData/*0:0*/ u_exec0__DOT__branch_d_request_o;
        CData/*1:0*/ u_exec0__DOT__branch_d_priv_o;
        CData/*4:0*/ u_exec0__DOT__shamt_r;
        CData/*3:0*/ u_exec0__DOT__alu_func_r;
        CData/*0:0*/ u_exec0__DOT__branch_r;
        CData/*0:0*/ u_exec0__DOT__branch_taken_r;
        CData/*0:0*/ u_exec0__DOT__branch_call_r;
        CData/*0:0*/ u_exec0__DOT__branch_ret_r;
    };
    struct {
        CData/*0:0*/ u_exec0__DOT__branch_jmp_r;
        CData/*0:0*/ u_exec0__DOT__branch_taken_q;
        CData/*0:0*/ u_exec0__DOT__branch_ntaken_q;
        CData/*0:0*/ u_exec0__DOT__branch_call_q;
        CData/*0:0*/ u_exec0__DOT__branch_ret_q;
        CData/*0:0*/ u_exec0__DOT__branch_jmp_q;
        CData/*3:0*/ u_exec0__DOT__u_alu__DOT__alu_op_i;
        CData/*0:0*/ u_exec1__DOT__clk_i;
        CData/*0:0*/ u_exec1__DOT__rst_i;
        CData/*0:0*/ u_exec1__DOT__opcode_valid_i;
        CData/*0:0*/ u_exec1__DOT__opcode_invalid_i;
        CData/*4:0*/ u_exec1__DOT__opcode_rd_idx_i;
        CData/*4:0*/ u_exec1__DOT__opcode_ra_idx_i;
        CData/*4:0*/ u_exec1__DOT__opcode_rb_idx_i;
        CData/*0:0*/ u_exec1__DOT__hold_i;
        CData/*0:0*/ u_exec1__DOT__branch_request_o;
        CData/*0:0*/ u_exec1__DOT__branch_is_taken_o;
        CData/*0:0*/ u_exec1__DOT__branch_is_not_taken_o;
        CData/*0:0*/ u_exec1__DOT__branch_is_call_o;
        CData/*0:0*/ u_exec1__DOT__branch_is_ret_o;
        CData/*0:0*/ u_exec1__DOT__branch_is_jmp_o;
        CData/*0:0*/ u_exec1__DOT__branch_d_request_o;
        CData/*1:0*/ u_exec1__DOT__branch_d_priv_o;
        CData/*4:0*/ u_exec1__DOT__shamt_r;
        CData/*3:0*/ u_exec1__DOT__alu_func_r;
        CData/*0:0*/ u_exec1__DOT__branch_r;
        CData/*0:0*/ u_exec1__DOT__branch_taken_r;
        CData/*0:0*/ u_exec1__DOT__branch_call_r;
        CData/*0:0*/ u_exec1__DOT__branch_ret_r;
        CData/*0:0*/ u_exec1__DOT__branch_jmp_r;
        CData/*0:0*/ u_exec1__DOT__branch_taken_q;
        CData/*0:0*/ u_exec1__DOT__branch_ntaken_q;
        CData/*0:0*/ u_exec1__DOT__branch_call_q;
        CData/*0:0*/ u_exec1__DOT__branch_ret_q;
        CData/*0:0*/ u_exec1__DOT__branch_jmp_q;
        CData/*3:0*/ u_exec1__DOT__u_alu__DOT__alu_op_i;
        CData/*0:0*/ __Vfunc_u_exec0__DOT__less_than_signed__0__Vfuncout;
        CData/*0:0*/ __Vfunc_u_exec0__DOT__greater_than_signed__1__Vfuncout;
        CData/*0:0*/ __Vfunc_u_exec1__DOT__less_than_signed__2__Vfuncout;
        CData/*0:0*/ __Vfunc_u_exec1__DOT__greater_than_signed__3__Vfuncout;
        VL_IN16(mem_d_resp_tag_i,10,0);
        VL_OUT16(mem_d_req_tag_o,10,0);
        SData/*10:0*/ mmu_lsu_resp_tag_w;
        SData/*10:0*/ mmu_lsu_req_tag_w;
        SData/*11:0*/ csr_writeback_waddr_w;
        SData/*8:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__global_history_real_q;
        SData/*8:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__global_history_q;
        SData/*8:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__gshare_wr_entry_w;
        SData/*8:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__gshare_rd_entry_w;
        SData/*8:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__bht_wr_entry_w;
        SData/*8:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__bht_rd_entry_w;
        SData/*15:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__u_lru__DOT__lfsr_q;
        SData/*10:0*/ u_mmu__DOT__lsu_in_req_tag_i;
        SData/*10:0*/ u_mmu__DOT__lsu_out_resp_tag_i;
        SData/*10:0*/ u_mmu__DOT__lsu_in_resp_tag_o;
        SData/*10:0*/ u_mmu__DOT__lsu_out_req_tag_o;
        SData/*10:0*/ u_lsu__DOT__mem_resp_tag_i;
        SData/*10:0*/ u_lsu__DOT__mem_req_tag_o;
        SData/*15:0*/ u_exec0__DOT__u_alu__DOT__shift_right_fill_r;
        SData/*15:0*/ u_exec1__DOT__u_alu__DOT__shift_right_fill_r;
        VL_IN(mem_d_data_rd_i,31,0);
        VL_IN(reset_vector_i,31,0);
        VL_IN(cpu_id_i,31,0);
        VL_OUT(mem_d_addr_o,31,0);
    };
    struct {
        VL_OUT(mem_d_data_wr_o,31,0);
        VL_OUT(mem_i_pc_o,31,0);
        IData/*31:0*/ lsu_opcode_pc_w;
        IData/*31:0*/ branch_exec0_source_w;
        IData/*31:0*/ csr_opcode_rb_operand_w;
        IData/*31:0*/ writeback_mem_value_w;
        IData/*31:0*/ writeback_div_value_w;
        IData/*31:0*/ fetch0_pc_w;
        IData/*31:0*/ branch_exec0_pc_w;
        IData/*31:0*/ opcode0_pc_w;
        IData/*31:0*/ opcode0_ra_operand_w;
        IData/*31:0*/ opcode0_rb_operand_w;
        IData/*31:0*/ fetch1_instr_w;
        IData/*31:0*/ csr_writeback_exception_addr_w;
        IData/*31:0*/ csr_opcode_pc_w;
        IData/*31:0*/ branch_info_pc_w;
        IData/*31:0*/ mmu_lsu_data_wr_w;
        IData/*31:0*/ branch_exec1_source_w;
        IData/*31:0*/ mul_opcode_opcode_w;
        IData/*31:0*/ branch_d_exec0_pc_w;
        IData/*31:0*/ branch_pc_w;
        IData/*31:0*/ opcode1_pc_w;
        IData/*31:0*/ branch_csr_pc_w;
        IData/*31:0*/ mul_opcode_pc_w;
        IData/*31:0*/ mul_opcode_rb_operand_w;
        IData/*31:0*/ mul_opcode_ra_operand_w;
        IData/*31:0*/ writeback_exec1_value_w;
        IData/*31:0*/ opcode1_rb_operand_w;
        IData/*31:0*/ mmu_lsu_addr_w;
        IData/*31:0*/ lsu_opcode_ra_operand_w;
        IData/*31:0*/ branch_exec1_pc_w;
        IData/*31:0*/ csr_opcode_ra_operand_w;
        IData/*31:0*/ opcode0_opcode_w;
        IData/*31:0*/ opcode1_ra_operand_w;
        IData/*31:0*/ mmu_ifetch_pc_w;
        IData/*31:0*/ opcode1_opcode_w;
        IData/*31:0*/ lsu_opcode_opcode_w;
        IData/*31:0*/ mmu_satp_w;
        IData/*31:0*/ csr_result_e1_wdata_w;
        IData/*31:0*/ writeback_exec0_value_w;
        IData/*31:0*/ fetch1_pc_w;
        IData/*31:0*/ csr_writeback_wdata_w;
        IData/*31:0*/ csr_result_e1_value_w;
        IData/*31:0*/ fetch0_instr_w;
        IData/*31:0*/ csr_opcode_opcode_w;
        IData/*31:0*/ mmu_lsu_data_rd_w;
        IData/*31:0*/ writeback_mul_value_w;
        IData/*31:0*/ lsu_opcode_rb_operand_w;
        IData/*31:0*/ branch_info_source_w;
        IData/*31:0*/ branch_d_exec1_pc_w;
        IData/*31:0*/ csr_writeback_exception_pc_w;
        IData/*31:0*/ u_frontend__DOT__branch_pc_i;
        IData/*31:0*/ u_frontend__DOT__branch_info_source_i;
        IData/*31:0*/ u_frontend__DOT__branch_info_pc_i;
        IData/*31:0*/ u_frontend__DOT__icache_pc_o;
        IData/*31:0*/ u_frontend__DOT__fetch0_instr_o;
        IData/*31:0*/ u_frontend__DOT__fetch0_pc_o;
        IData/*31:0*/ u_frontend__DOT__fetch1_instr_o;
        IData/*31:0*/ u_frontend__DOT__fetch1_pc_o;
        IData/*31:0*/ u_frontend__DOT__next_pc_f_w;
        IData/*31:0*/ u_frontend__DOT__fetch_pc_f_w;
        IData/*31:0*/ u_frontend__DOT__fetch_pc_w;
        IData/*31:0*/ u_frontend__DOT__u_npc__DOT__branch_source_i;
        IData/*31:0*/ u_frontend__DOT__u_npc__DOT__branch_pc_i;
    };
    struct {
        IData/*31:0*/ u_frontend__DOT__u_npc__DOT__pc_f_i;
        IData/*31:0*/ u_frontend__DOT__u_npc__DOT__next_pc_f_o;
        IData/*31:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_next_pc_w;
        IData/*31:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__ras_pc_pred_w;
        IData/*31:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__i3;
        IData/*31:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__i4;
        IData/*31:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_next_pc_r;
        IData/*31:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__i0;
        IData/*31:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__i1;
        IData/*31:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__i2;
        IData/*31:0*/ u_frontend__DOT__u_decode__DOT__fetch_in_pc_i;
        IData/*31:0*/ u_frontend__DOT__u_decode__DOT__branch_pc_i;
        IData/*31:0*/ u_frontend__DOT__u_decode__DOT__fetch_out0_instr_o;
        IData/*31:0*/ u_frontend__DOT__u_decode__DOT__fetch_out0_pc_o;
        IData/*31:0*/ u_frontend__DOT__u_decode__DOT__fetch_out1_instr_o;
        IData/*31:0*/ u_frontend__DOT__u_decode__DOT__fetch_out1_pc_o;
        IData/*31:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__pc_in_i;
        IData/*31:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__pc0_out_o;
        IData/*31:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__data0_out_o;
        IData/*31:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__pc1_out_o;
        IData/*31:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__data1_out_o;
        IData/*31:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__i;
        IData/*31:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT__opcode_i;
        IData/*31:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT__opcode_i;
        IData/*31:0*/ u_frontend__DOT__u_fetch__DOT__branch_pc_i;
        IData/*31:0*/ u_frontend__DOT__u_fetch__DOT__next_pc_f_i;
        IData/*31:0*/ u_frontend__DOT__u_fetch__DOT__fetch_pc_o;
        IData/*31:0*/ u_frontend__DOT__u_fetch__DOT__icache_pc_o;
        IData/*31:0*/ u_frontend__DOT__u_fetch__DOT__pc_f_o;
        IData/*31:0*/ u_frontend__DOT__u_fetch__DOT__branch_pc_q;
        IData/*31:0*/ u_frontend__DOT__u_fetch__DOT__branch_pc_w;
        IData/*31:0*/ u_frontend__DOT__u_fetch__DOT__pc_f_q;
        IData/*31:0*/ u_frontend__DOT__u_fetch__DOT__pc_d_q;
        IData/*31:0*/ u_frontend__DOT__u_fetch__DOT__icache_pc_w;
        VlWide<4>/*99:0*/ u_frontend__DOT__u_fetch__DOT__skid_buffer_q;
        IData/*31:0*/ u_mmu__DOT__satp_i;
        IData/*31:0*/ u_mmu__DOT__fetch_in_pc_i;
        IData/*31:0*/ u_mmu__DOT__lsu_in_addr_i;
        IData/*31:0*/ u_mmu__DOT__lsu_in_data_wr_i;
        IData/*31:0*/ u_mmu__DOT__lsu_out_data_rd_i;
        IData/*31:0*/ u_mmu__DOT__fetch_out_pc_o;
        IData/*31:0*/ u_mmu__DOT__lsu_in_data_rd_o;
        IData/*31:0*/ u_mmu__DOT__lsu_out_addr_o;
        IData/*31:0*/ u_mmu__DOT__lsu_out_data_wr_o;
        IData/*31:0*/ u_lsu__DOT__opcode_opcode_i;
        IData/*31:0*/ u_lsu__DOT__opcode_pc_i;
        IData/*31:0*/ u_lsu__DOT__opcode_ra_operand_i;
        IData/*31:0*/ u_lsu__DOT__opcode_rb_operand_i;
        IData/*31:0*/ u_lsu__DOT__mem_data_rd_i;
        IData/*31:0*/ u_lsu__DOT__mem_addr_o;
        IData/*31:0*/ u_lsu__DOT__mem_data_wr_o;
        IData/*31:0*/ u_lsu__DOT__writeback_value_o;
        IData/*31:0*/ u_lsu__DOT__mem_addr_q;
        IData/*31:0*/ u_lsu__DOT__mem_data_wr_q;
        IData/*31:0*/ u_lsu__DOT__mem_addr_r;
        IData/*31:0*/ u_lsu__DOT__mem_data_r;
        IData/*31:0*/ u_lsu__DOT__resp_addr_w;
        IData/*31:0*/ u_lsu__DOT__wb_result_r;
        IData/*31:0*/ u_lsu__DOT__u_lsu_request__DOT__i;
        IData/*31:0*/ u_mul__DOT__opcode_opcode_i;
        IData/*31:0*/ u_mul__DOT__opcode_pc_i;
        IData/*31:0*/ u_mul__DOT__opcode_ra_operand_i;
        IData/*31:0*/ u_mul__DOT__opcode_rb_operand_i;
        IData/*31:0*/ u_mul__DOT__writeback_value_o;
    };
    struct {
        IData/*31:0*/ u_mul__DOT__result_e2_q;
        IData/*31:0*/ u_mul__DOT__result_e3_q;
        VlWide<3>/*64:0*/ u_mul__DOT__mult_result_w;
        IData/*31:0*/ u_mul__DOT__result_r;
        IData/*31:0*/ u_div__DOT__opcode_opcode_i;
        IData/*31:0*/ u_div__DOT__opcode_pc_i;
        IData/*31:0*/ u_div__DOT__opcode_ra_operand_i;
        IData/*31:0*/ u_div__DOT__opcode_rb_operand_i;
        IData/*31:0*/ u_div__DOT__writeback_value_o;
        IData/*31:0*/ u_div__DOT__wb_result_q;
        IData/*31:0*/ u_div__DOT__dividend_q;
        IData/*31:0*/ u_div__DOT__quotient_q;
        IData/*31:0*/ u_div__DOT__q_mask_q;
        IData/*31:0*/ u_div__DOT__last_a_q;
        IData/*31:0*/ u_div__DOT__last_b_q;
        IData/*31:0*/ u_div__DOT__div_result_r;
        IData/*31:0*/ u_exec0__DOT__opcode_opcode_i;
        IData/*31:0*/ u_exec0__DOT__opcode_pc_i;
        IData/*31:0*/ u_exec0__DOT__opcode_ra_operand_i;
        IData/*31:0*/ u_exec0__DOT__opcode_rb_operand_i;
        IData/*31:0*/ u_exec0__DOT__branch_source_o;
        IData/*31:0*/ u_exec0__DOT__branch_pc_o;
        IData/*31:0*/ u_exec0__DOT__branch_d_pc_o;
        IData/*31:0*/ u_exec0__DOT__writeback_value_o;
        IData/*31:0*/ u_exec0__DOT__imm20_r;
        IData/*31:0*/ u_exec0__DOT__imm12_r;
        IData/*31:0*/ u_exec0__DOT__bimm_r;
        IData/*31:0*/ u_exec0__DOT__jimm20_r;
        IData/*31:0*/ u_exec0__DOT__alu_input_a_r;
        IData/*31:0*/ u_exec0__DOT__alu_input_b_r;
        IData/*31:0*/ u_exec0__DOT__alu_p_w;
        IData/*31:0*/ u_exec0__DOT__result_q;
        IData/*31:0*/ u_exec0__DOT__less_than_signed__Vstatic__v;
        IData/*31:0*/ u_exec0__DOT__greater_than_signed__Vstatic__v;
        IData/*31:0*/ u_exec0__DOT__branch_target_r;
        IData/*31:0*/ u_exec0__DOT__pc_x_q;
        IData/*31:0*/ u_exec0__DOT__pc_m_q;
        IData/*31:0*/ u_exec0__DOT__u_alu__DOT__alu_a_i;
        IData/*31:0*/ u_exec0__DOT__u_alu__DOT__alu_b_i;
        IData/*31:0*/ u_exec0__DOT__u_alu__DOT__alu_p_o;
        IData/*31:0*/ u_exec0__DOT__u_alu__DOT__result_r;
        IData/*31:0*/ u_exec0__DOT__u_alu__DOT__shift_right_1_r;
        IData/*31:0*/ u_exec0__DOT__u_alu__DOT__shift_right_2_r;
        IData/*31:0*/ u_exec0__DOT__u_alu__DOT__shift_right_4_r;
        IData/*31:0*/ u_exec0__DOT__u_alu__DOT__shift_right_8_r;
        IData/*31:0*/ u_exec0__DOT__u_alu__DOT__shift_left_1_r;
        IData/*31:0*/ u_exec0__DOT__u_alu__DOT__shift_left_2_r;
        IData/*31:0*/ u_exec0__DOT__u_alu__DOT__shift_left_4_r;
        IData/*31:0*/ u_exec0__DOT__u_alu__DOT__shift_left_8_r;
        IData/*31:0*/ u_exec0__DOT__u_alu__DOT__sub_res_w;
        IData/*31:0*/ u_exec1__DOT__opcode_opcode_i;
        IData/*31:0*/ u_exec1__DOT__opcode_pc_i;
        IData/*31:0*/ u_exec1__DOT__opcode_ra_operand_i;
        IData/*31:0*/ u_exec1__DOT__opcode_rb_operand_i;
        IData/*31:0*/ u_exec1__DOT__branch_source_o;
        IData/*31:0*/ u_exec1__DOT__branch_pc_o;
        IData/*31:0*/ u_exec1__DOT__branch_d_pc_o;
        IData/*31:0*/ u_exec1__DOT__writeback_value_o;
        IData/*31:0*/ u_exec1__DOT__imm20_r;
        IData/*31:0*/ u_exec1__DOT__imm12_r;
        IData/*31:0*/ u_exec1__DOT__bimm_r;
        IData/*31:0*/ u_exec1__DOT__jimm20_r;
        IData/*31:0*/ u_exec1__DOT__alu_input_a_r;
        IData/*31:0*/ u_exec1__DOT__alu_input_b_r;
    };
    struct {
        IData/*31:0*/ u_exec1__DOT__alu_p_w;
        IData/*31:0*/ u_exec1__DOT__result_q;
        IData/*31:0*/ u_exec1__DOT__less_than_signed__Vstatic__v;
        IData/*31:0*/ u_exec1__DOT__greater_than_signed__Vstatic__v;
        IData/*31:0*/ u_exec1__DOT__branch_target_r;
        IData/*31:0*/ u_exec1__DOT__pc_x_q;
        IData/*31:0*/ u_exec1__DOT__pc_m_q;
        IData/*31:0*/ u_exec1__DOT__u_alu__DOT__alu_a_i;
        IData/*31:0*/ u_exec1__DOT__u_alu__DOT__alu_b_i;
        IData/*31:0*/ u_exec1__DOT__u_alu__DOT__alu_p_o;
        IData/*31:0*/ u_exec1__DOT__u_alu__DOT__result_r;
        IData/*31:0*/ u_exec1__DOT__u_alu__DOT__shift_right_1_r;
        IData/*31:0*/ u_exec1__DOT__u_alu__DOT__shift_right_2_r;
        IData/*31:0*/ u_exec1__DOT__u_alu__DOT__shift_right_4_r;
        IData/*31:0*/ u_exec1__DOT__u_alu__DOT__shift_right_8_r;
        IData/*31:0*/ u_exec1__DOT__u_alu__DOT__shift_left_1_r;
        IData/*31:0*/ u_exec1__DOT__u_alu__DOT__shift_left_2_r;
        IData/*31:0*/ u_exec1__DOT__u_alu__DOT__shift_left_4_r;
        IData/*31:0*/ u_exec1__DOT__u_alu__DOT__shift_left_8_r;
        IData/*31:0*/ u_exec1__DOT__u_alu__DOT__sub_res_w;
        IData/*31:0*/ __Vfunc_u_exec0__DOT__less_than_signed__0__x;
        IData/*31:0*/ __Vfunc_u_exec0__DOT__less_than_signed__0__y;
        IData/*31:0*/ __Vfunc_u_exec0__DOT__greater_than_signed__1__x;
        IData/*31:0*/ __Vfunc_u_exec0__DOT__greater_than_signed__1__y;
        IData/*31:0*/ __Vfunc_u_exec1__DOT__less_than_signed__2__x;
        IData/*31:0*/ __Vfunc_u_exec1__DOT__less_than_signed__2__y;
        IData/*31:0*/ __Vfunc_u_exec1__DOT__greater_than_signed__3__x;
        IData/*31:0*/ __Vfunc_u_exec1__DOT__greater_than_signed__3__y;
        VL_IN64(mem_i_inst_i,63,0);
        QData/*63:0*/ mmu_ifetch_inst_w;
        QData/*63:0*/ u_frontend__DOT__icache_inst_i;
        QData/*63:0*/ u_frontend__DOT__fetch_instr_w;
        QData/*63:0*/ u_frontend__DOT__u_decode__DOT__fetch_in_instr_i;
        QData/*63:0*/ u_frontend__DOT__u_decode__DOT____Vcellinp__genblk1__DOT__u_fifo__data_in_i;
        QData/*63:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__data_in_i;
        QData/*63:0*/ u_frontend__DOT__u_fetch__DOT__icache_inst_i;
        QData/*63:0*/ u_frontend__DOT__u_fetch__DOT__fetch_instr_o;
        QData/*63:0*/ u_mmu__DOT__fetch_out_inst_i;
        QData/*63:0*/ u_mmu__DOT__fetch_in_inst_o;
        QData/*35:0*/ u_lsu__DOT____Vcellinp__u_lsu_request__data_in_i;
        QData/*35:0*/ u_lsu__DOT__u_lsu_request__DOT__data_in_i;
        QData/*35:0*/ u_lsu__DOT__u_lsu_request__DOT__data_out_o;
        QData/*32:0*/ u_mul__DOT__operand_a_e1_q;
        QData/*32:0*/ u_mul__DOT__operand_b_e1_q;
        QData/*32:0*/ u_mul__DOT__operand_b_r;
        QData/*32:0*/ u_mul__DOT__operand_a_r;
        QData/*62:0*/ u_div__DOT__divisor_q;
        VlUnpacked<IData/*31:0*/, 8> u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__ras_stack_q;
        VlUnpacked<CData/*1:0*/, 512> u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__bht_sat_q;
        VlUnpacked<IData/*31:0*/, 32> u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_pc_q;
        VlUnpacked<IData/*31:0*/, 32> u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_target_q;
        VlUnpacked<CData/*0:0*/, 32> u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_is_call_q;
        VlUnpacked<CData/*0:0*/, 32> u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_is_ret_q;
        VlUnpacked<CData/*0:0*/, 32> u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_is_jmp_q;
        VlUnpacked<IData/*31:0*/, 2> u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__pc_q;
        VlUnpacked<CData/*0:0*/, 2> u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__valid0_q;
        VlUnpacked<CData/*0:0*/, 2> u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__valid1_q;
        VlUnpacked<CData/*1:0*/, 2> u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__info0_q;
        VlUnpacked<CData/*1:0*/, 2> u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__info1_q;
        VlUnpacked<QData/*63:0*/, 2> u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__ram_q;
        VlUnpacked<QData/*35:0*/, 2> u_lsu__DOT__u_lsu_request__DOT__ram_q;
    };

    // INTERNAL VARIABLES
    Vbiriscv_mem_top__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr SData/*15:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__u_lru__DOT__INITIAL_VALUE = 1U;
    static constexpr SData/*15:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__u_lru__DOT__TAP_VALUE = 0xb400U;
    static constexpr IData/*31:0*/ SUPPORT_BRANCH_PREDICTION = 1U;
    static constexpr IData/*31:0*/ SUPPORT_MULDIV = 1U;
    static constexpr IData/*31:0*/ SUPPORT_SUPER = 0U;
    static constexpr IData/*31:0*/ SUPPORT_MMU = 0U;
    static constexpr IData/*31:0*/ SUPPORT_DUAL_ISSUE = 1U;
    static constexpr IData/*31:0*/ SUPPORT_LOAD_BYPASS = 1U;
    static constexpr IData/*31:0*/ SUPPORT_MUL_BYPASS = 1U;
    static constexpr IData/*31:0*/ SUPPORT_REGFILE_XILINX = 0U;
    static constexpr IData/*31:0*/ EXTRA_DECODE_STAGE = 0U;
    static constexpr IData/*31:0*/ MEM_CACHE_ADDR_MIN = 0x80000000U;
    static constexpr IData/*31:0*/ MEM_CACHE_ADDR_MAX = 0x8fffffffU;
    static constexpr IData/*31:0*/ NUM_BTB_ENTRIES = 0x00000020U;
    static constexpr IData/*31:0*/ NUM_BTB_ENTRIES_W = 5U;
    static constexpr IData/*31:0*/ NUM_BHT_ENTRIES = 0x00000200U;
    static constexpr IData/*31:0*/ NUM_BHT_ENTRIES_W = 9U;
    static constexpr IData/*31:0*/ RAS_ENABLE = 1U;
    static constexpr IData/*31:0*/ GSHARE_ENABLE = 0U;
    static constexpr IData/*31:0*/ BHT_ENABLE = 1U;
    static constexpr IData/*31:0*/ NUM_RAS_ENTRIES = 8U;
    static constexpr IData/*31:0*/ NUM_RAS_ENTRIES_W = 3U;
    static constexpr IData/*31:0*/ u_frontend__DOT__SUPPORT_BRANCH_PREDICTION = 1U;
    static constexpr IData/*31:0*/ u_frontend__DOT__SUPPORT_MULDIV = 1U;
    static constexpr IData/*31:0*/ u_frontend__DOT__SUPPORT_MMU = 0U;
    static constexpr IData/*31:0*/ u_frontend__DOT__EXTRA_DECODE_STAGE = 0U;
    static constexpr IData/*31:0*/ u_frontend__DOT__NUM_BTB_ENTRIES = 0x00000020U;
    static constexpr IData/*31:0*/ u_frontend__DOT__NUM_BTB_ENTRIES_W = 5U;
    static constexpr IData/*31:0*/ u_frontend__DOT__NUM_BHT_ENTRIES = 0x00000200U;
    static constexpr IData/*31:0*/ u_frontend__DOT__NUM_BHT_ENTRIES_W = 9U;
    static constexpr IData/*31:0*/ u_frontend__DOT__RAS_ENABLE = 1U;
    static constexpr IData/*31:0*/ u_frontend__DOT__GSHARE_ENABLE = 0U;
    static constexpr IData/*31:0*/ u_frontend__DOT__BHT_ENABLE = 1U;
    static constexpr IData/*31:0*/ u_frontend__DOT__NUM_RAS_ENTRIES = 8U;
    static constexpr IData/*31:0*/ u_frontend__DOT__NUM_RAS_ENTRIES_W = 3U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_npc__DOT__SUPPORT_BRANCH_PREDICTION = 1U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_npc__DOT__NUM_BTB_ENTRIES = 0x00000020U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_npc__DOT__NUM_BTB_ENTRIES_W = 5U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_npc__DOT__NUM_BHT_ENTRIES = 0x00000200U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_npc__DOT__NUM_BHT_ENTRIES_W = 9U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_npc__DOT__RAS_ENABLE = 1U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_npc__DOT__GSHARE_ENABLE = 0U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_npc__DOT__BHT_ENABLE = 1U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_npc__DOT__NUM_RAS_ENTRIES = 8U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_npc__DOT__NUM_RAS_ENTRIES_W = 3U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_npc__DOT__RAS_INVALID = 1U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__u_lru__DOT__DEPTH = 0x00000020U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__u_lru__DOT__ADDR_W = 5U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_decode__DOT__SUPPORT_MULDIV = 1U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_decode__DOT__EXTRA_DECODE_STAGE = 0U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__DEPTH = 2U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__ADDR_W = 1U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__OPC_INFO_W = 2U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__COUNT_W = 2U;
    static constexpr IData/*31:0*/ u_frontend__DOT__u_fetch__DOT__SUPPORT_MMU = 0U;
    static constexpr IData/*31:0*/ u_mmu__DOT__MEM_CACHE_ADDR_MIN = 0x80000000U;
    static constexpr IData/*31:0*/ u_mmu__DOT__MEM_CACHE_ADDR_MAX = 0x8fffffffU;
    static constexpr IData/*31:0*/ u_mmu__DOT__SUPPORT_MMU = 0U;
    static constexpr IData/*31:0*/ u_mmu__DOT__STATE_W = 2U;
    static constexpr IData/*31:0*/ u_mmu__DOT__STATE_IDLE = 0U;
    static constexpr IData/*31:0*/ u_mmu__DOT__STATE_LEVEL_FIRST = 1U;
    static constexpr IData/*31:0*/ u_mmu__DOT__STATE_LEVEL_SECOND = 2U;
    static constexpr IData/*31:0*/ u_mmu__DOT__STATE_UPDATE = 3U;
    static constexpr IData/*31:0*/ u_lsu__DOT__MEM_CACHE_ADDR_MIN = 0x80000000U;
    static constexpr IData/*31:0*/ u_lsu__DOT__MEM_CACHE_ADDR_MAX = 0x8fffffffU;
    static constexpr IData/*31:0*/ u_lsu__DOT__u_lsu_request__DOT__WIDTH = 0x00000024U;
    static constexpr IData/*31:0*/ u_lsu__DOT__u_lsu_request__DOT__DEPTH = 2U;
    static constexpr IData/*31:0*/ u_lsu__DOT__u_lsu_request__DOT__ADDR_W = 1U;
    static constexpr IData/*31:0*/ u_lsu__DOT__u_lsu_request__DOT__COUNT_W = 2U;
    static constexpr IData/*31:0*/ u_mul__DOT__MULT_STAGES = 2U;

    // CONSTRUCTORS
    Vbiriscv_mem_top_riscv_core(Vbiriscv_mem_top__Syms* symsp, const char* v__name);
    ~Vbiriscv_mem_top_riscv_core();
    VL_UNCOPYABLE(Vbiriscv_mem_top_riscv_core);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
