// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vbiriscv_mem_top.h for the primary calling header

#ifndef VERILATED_VBIRISCV_MEM_TOP_BIRISCV_ISSUE_H_
#define VERILATED_VBIRISCV_MEM_TOP_BIRISCV_ISSUE_H_  // guard

#include "verilated.h"
class Vbiriscv_mem_top_biriscv_regfile;


class Vbiriscv_mem_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vbiriscv_mem_top_biriscv_issue final : public VerilatedModule {
  public:
    // CELLS
    Vbiriscv_mem_top_biriscv_regfile* u_regfile;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk_i,0,0);
        VL_IN8(rst_i,0,0);
        VL_IN8(fetch0_valid_i,0,0);
        VL_IN8(fetch0_fault_fetch_i,0,0);
        VL_IN8(fetch0_fault_page_i,0,0);
        VL_IN8(fetch0_instr_exec_i,0,0);
        VL_IN8(fetch0_instr_lsu_i,0,0);
        VL_IN8(fetch0_instr_branch_i,0,0);
        VL_IN8(fetch0_instr_mul_i,0,0);
        VL_IN8(fetch0_instr_div_i,0,0);
        VL_IN8(fetch0_instr_csr_i,0,0);
        VL_IN8(fetch0_instr_rd_valid_i,0,0);
        VL_IN8(fetch0_instr_invalid_i,0,0);
        VL_IN8(fetch1_valid_i,0,0);
        VL_IN8(fetch1_fault_fetch_i,0,0);
        VL_IN8(fetch1_fault_page_i,0,0);
        VL_IN8(fetch1_instr_exec_i,0,0);
        VL_IN8(fetch1_instr_lsu_i,0,0);
        VL_IN8(fetch1_instr_branch_i,0,0);
        VL_IN8(fetch1_instr_mul_i,0,0);
        VL_IN8(fetch1_instr_div_i,0,0);
        VL_IN8(fetch1_instr_csr_i,0,0);
        VL_IN8(fetch1_instr_rd_valid_i,0,0);
        VL_IN8(fetch1_instr_invalid_i,0,0);
        VL_IN8(branch_exec0_request_i,0,0);
        VL_IN8(branch_exec0_is_taken_i,0,0);
        VL_IN8(branch_exec0_is_not_taken_i,0,0);
        VL_IN8(branch_exec0_is_call_i,0,0);
        VL_IN8(branch_exec0_is_ret_i,0,0);
        VL_IN8(branch_exec0_is_jmp_i,0,0);
        VL_IN8(branch_d_exec0_request_i,0,0);
        VL_IN8(branch_d_exec0_priv_i,1,0);
        VL_IN8(branch_exec1_request_i,0,0);
        VL_IN8(branch_exec1_is_taken_i,0,0);
        VL_IN8(branch_exec1_is_not_taken_i,0,0);
        VL_IN8(branch_exec1_is_call_i,0,0);
        VL_IN8(branch_exec1_is_ret_i,0,0);
        VL_IN8(branch_exec1_is_jmp_i,0,0);
        VL_IN8(branch_d_exec1_request_i,0,0);
        VL_IN8(branch_d_exec1_priv_i,1,0);
        VL_IN8(branch_csr_request_i,0,0);
        VL_IN8(branch_csr_priv_i,1,0);
        VL_IN8(writeback_mem_valid_i,0,0);
        VL_IN8(writeback_mem_exception_i,5,0);
        VL_IN8(writeback_div_valid_i,0,0);
        VL_IN8(csr_result_e1_write_i,0,0);
        VL_IN8(csr_result_e1_exception_i,5,0);
        VL_IN8(lsu_stall_i,0,0);
        VL_IN8(take_interrupt_i,0,0);
        VL_OUT8(fetch0_accept_o,0,0);
        VL_OUT8(fetch1_accept_o,0,0);
        VL_OUT8(branch_request_o,0,0);
        VL_OUT8(branch_priv_o,1,0);
        VL_OUT8(branch_info_request_o,0,0);
        VL_OUT8(branch_info_is_taken_o,0,0);
        VL_OUT8(branch_info_is_not_taken_o,0,0);
        VL_OUT8(branch_info_is_call_o,0,0);
        VL_OUT8(branch_info_is_ret_o,0,0);
        VL_OUT8(branch_info_is_jmp_o,0,0);
        VL_OUT8(exec0_opcode_valid_o,0,0);
        VL_OUT8(exec1_opcode_valid_o,0,0);
        VL_OUT8(lsu_opcode_valid_o,0,0);
        VL_OUT8(csr_opcode_valid_o,0,0);
        VL_OUT8(mul_opcode_valid_o,0,0);
    };
    struct {
        VL_OUT8(div_opcode_valid_o,0,0);
        VL_OUT8(opcode0_invalid_o,0,0);
        VL_OUT8(opcode0_rd_idx_o,4,0);
        VL_OUT8(opcode0_ra_idx_o,4,0);
        VL_OUT8(opcode0_rb_idx_o,4,0);
        VL_OUT8(opcode1_invalid_o,0,0);
        VL_OUT8(opcode1_rd_idx_o,4,0);
        VL_OUT8(opcode1_ra_idx_o,4,0);
        VL_OUT8(opcode1_rb_idx_o,4,0);
        VL_OUT8(lsu_opcode_invalid_o,0,0);
        VL_OUT8(lsu_opcode_rd_idx_o,4,0);
        VL_OUT8(lsu_opcode_ra_idx_o,4,0);
        VL_OUT8(lsu_opcode_rb_idx_o,4,0);
        VL_OUT8(mul_opcode_invalid_o,0,0);
        VL_OUT8(mul_opcode_rd_idx_o,4,0);
        VL_OUT8(mul_opcode_ra_idx_o,4,0);
        VL_OUT8(mul_opcode_rb_idx_o,4,0);
        VL_OUT8(csr_opcode_invalid_o,0,0);
        VL_OUT8(csr_opcode_rd_idx_o,4,0);
        VL_OUT8(csr_opcode_ra_idx_o,4,0);
        VL_OUT8(csr_opcode_rb_idx_o,4,0);
        VL_OUT8(csr_writeback_write_o,0,0);
        VL_OUT8(csr_writeback_exception_o,5,0);
        VL_OUT8(exec0_hold_o,0,0);
        VL_OUT8(exec1_hold_o,0,0);
        VL_OUT8(mul_hold_o,0,0);
        VL_OUT8(interrupt_inhibit_o,0,0);
        CData/*0:0*/ enable_dual_issue_w;
        CData/*0:0*/ enable_muldiv_w;
        CData/*0:0*/ enable_mul_bypass_w;
        CData/*0:0*/ stall_w;
        CData/*0:0*/ squash_w;
        CData/*0:0*/ single_issue_w;
        CData/*0:0*/ dual_issue_w;
        CData/*1:0*/ priv_x_q;
        CData/*0:0*/ mispredicted_r;
        CData/*0:0*/ slot0_valid_r;
        CData/*0:0*/ slot1_valid_r;
        CData/*0:0*/ opcode_a_valid_r;
        CData/*0:0*/ opcode_b_valid_r;
        CData/*1:0*/ opcode_a_fault_r;
        CData/*1:0*/ opcode_b_fault_r;
        CData/*4:0*/ issue_a_ra_idx_w;
        CData/*4:0*/ issue_a_rb_idx_w;
        CData/*4:0*/ issue_a_rd_idx_w;
        CData/*0:0*/ issue_a_sb_alloc_w;
        CData/*0:0*/ issue_a_exec_w;
        CData/*0:0*/ issue_a_lsu_w;
        CData/*0:0*/ issue_a_branch_w;
        CData/*0:0*/ issue_a_mul_w;
        CData/*0:0*/ issue_a_div_w;
        CData/*0:0*/ issue_a_csr_w;
        CData/*0:0*/ issue_a_invalid_w;
        CData/*4:0*/ issue_b_ra_idx_w;
        CData/*4:0*/ issue_b_rb_idx_w;
        CData/*4:0*/ issue_b_rd_idx_w;
        CData/*0:0*/ issue_b_sb_alloc_w;
        CData/*0:0*/ issue_b_exec_w;
        CData/*0:0*/ issue_b_lsu_w;
        CData/*0:0*/ issue_b_branch_w;
        CData/*0:0*/ issue_b_mul_w;
        CData/*0:0*/ issue_b_div_w;
        CData/*0:0*/ issue_b_csr_w;
        CData/*0:0*/ issue_b_invalid_w;
    };
    struct {
        CData/*0:0*/ pipe0_squash_e1_e2_w;
        CData/*0:0*/ pipe1_squash_e1_e2_w;
        CData/*0:0*/ opcode_a_issue_r;
        CData/*0:0*/ opcode_a_accept_r;
        CData/*0:0*/ pipe0_stall_raw_w;
        CData/*0:0*/ pipe0_load_e1_w;
        CData/*0:0*/ pipe0_store_e1_w;
        CData/*0:0*/ pipe0_mul_e1_w;
        CData/*0:0*/ pipe0_branch_e1_w;
        CData/*4:0*/ pipe0_rd_e1_w;
        CData/*0:0*/ pipe0_load_e2_w;
        CData/*0:0*/ pipe0_mul_e2_w;
        CData/*4:0*/ pipe0_rd_e2_w;
        CData/*0:0*/ pipe0_valid_wb_w;
        CData/*0:0*/ pipe0_csr_wb_w;
        CData/*4:0*/ pipe0_rd_wb_w;
        CData/*5:0*/ pipe0_exception_wb_w;
        CData/*5:0*/ issue_a_fault_w;
        CData/*0:0*/ opcode_b_issue_r;
        CData/*0:0*/ opcode_b_accept_r;
        CData/*0:0*/ pipe1_stall_raw_w;
        CData/*0:0*/ pipe1_load_e1_w;
        CData/*0:0*/ pipe1_store_e1_w;
        CData/*0:0*/ pipe1_mul_e1_w;
        CData/*0:0*/ pipe1_branch_e1_w;
        CData/*4:0*/ pipe1_rd_e1_w;
        CData/*0:0*/ pipe1_load_e2_w;
        CData/*0:0*/ pipe1_mul_e2_w;
        CData/*4:0*/ pipe1_rd_e2_w;
        CData/*0:0*/ pipe1_valid_wb_w;
        CData/*4:0*/ pipe1_rd_wb_w;
        CData/*5:0*/ pipe1_exception_wb_w;
        CData/*5:0*/ issue_b_fault_w;
        CData/*0:0*/ div_pending_q;
        CData/*0:0*/ csr_pending_q;
        CData/*0:0*/ pipe1_mux_lsu_r;
        CData/*0:0*/ pipe1_mux_mul_r;
        CData/*0:0*/ pipe1_ok_w;
        CData/*0:0*/ dual_issue_ok_w;
        CData/*4:0*/ v_pipe0_rs1_w;
        CData/*4:0*/ v_pipe0_rs2_w;
        CData/*4:0*/ v_pipe1_rs1_w;
        CData/*4:0*/ v_pipe1_rs2_w;
        CData/*0:0*/ u_pipe0_ctrl__DOT__clk_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__rst_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__issue_valid_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__issue_accept_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__issue_stall_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__issue_lsu_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__issue_csr_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__issue_div_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__issue_mul_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__issue_branch_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__issue_rd_valid_i;
        CData/*4:0*/ u_pipe0_ctrl__DOT__issue_rd_i;
        CData/*5:0*/ u_pipe0_ctrl__DOT__issue_exception_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__take_interrupt_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__issue_branch_taken_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__csr_result_write_e1_i;
        CData/*5:0*/ u_pipe0_ctrl__DOT__csr_result_exception_e1_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__load_e1_o;
        CData/*0:0*/ u_pipe0_ctrl__DOT__store_e1_o;
        CData/*0:0*/ u_pipe0_ctrl__DOT__mul_e1_o;
        CData/*0:0*/ u_pipe0_ctrl__DOT__branch_e1_o;
    };
    struct {
        CData/*4:0*/ u_pipe0_ctrl__DOT__rd_e1_o;
        CData/*0:0*/ u_pipe0_ctrl__DOT__mem_complete_i;
        CData/*5:0*/ u_pipe0_ctrl__DOT__mem_exception_e2_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__load_e2_o;
        CData/*0:0*/ u_pipe0_ctrl__DOT__mul_e2_o;
        CData/*4:0*/ u_pipe0_ctrl__DOT__rd_e2_o;
        CData/*0:0*/ u_pipe0_ctrl__DOT__div_complete_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__valid_wb_o;
        CData/*0:0*/ u_pipe0_ctrl__DOT__csr_wb_o;
        CData/*4:0*/ u_pipe0_ctrl__DOT__rd_wb_o;
        CData/*5:0*/ u_pipe0_ctrl__DOT__exception_wb_o;
        CData/*0:0*/ u_pipe0_ctrl__DOT__csr_write_wb_o;
        CData/*0:0*/ u_pipe0_ctrl__DOT__stall_o;
        CData/*0:0*/ u_pipe0_ctrl__DOT__squash_e1_e2_o;
        CData/*0:0*/ u_pipe0_ctrl__DOT__squash_e1_e2_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__squash_wb_i;
        CData/*0:0*/ u_pipe0_ctrl__DOT__squash_e1_e2_w;
        CData/*0:0*/ u_pipe0_ctrl__DOT__branch_misaligned_w;
        CData/*0:0*/ u_pipe0_ctrl__DOT__valid_e1_q;
        CData/*5:0*/ u_pipe0_ctrl__DOT__exception_e1_q;
        CData/*0:0*/ u_pipe0_ctrl__DOT__alu_e1_w;
        CData/*0:0*/ u_pipe0_ctrl__DOT__csr_e1_w;
        CData/*0:0*/ u_pipe0_ctrl__DOT__div_e1_w;
        CData/*0:0*/ u_pipe0_ctrl__DOT__valid_e2_q;
        CData/*0:0*/ u_pipe0_ctrl__DOT__csr_wr_e2_q;
        CData/*5:0*/ u_pipe0_ctrl__DOT__exception_e2_q;
        CData/*0:0*/ u_pipe0_ctrl__DOT__valid_e2_w;
        CData/*0:0*/ u_pipe0_ctrl__DOT__load_store_e2_w;
        CData/*5:0*/ u_pipe0_ctrl__DOT__exception_e2_r;
        CData/*0:0*/ u_pipe0_ctrl__DOT__squash_e1_e2_q;
        CData/*0:0*/ u_pipe0_ctrl__DOT__valid_wb_q;
        CData/*0:0*/ u_pipe0_ctrl__DOT__csr_wr_wb_q;
        CData/*5:0*/ u_pipe0_ctrl__DOT__exception_wb_q;
        CData/*0:0*/ u_pipe0_ctrl__DOT__complete_wb_w;
        CData/*0:0*/ u_pipe0_ctrl__DOT__u_trace_d__DOT__valid_i;
        CData/*4:0*/ u_pipe0_ctrl__DOT__u_trace_d__DOT__ra_idx_w;
        CData/*4:0*/ u_pipe0_ctrl__DOT__u_trace_d__DOT__rb_idx_w;
        CData/*4:0*/ u_pipe0_ctrl__DOT__u_trace_d__DOT__rd_idx_w;
        CData/*0:0*/ u_pipe0_ctrl__DOT__u_trace_wb__DOT__valid_i;
        CData/*4:0*/ u_pipe0_ctrl__DOT__u_trace_wb__DOT__ra_idx_w;
        CData/*4:0*/ u_pipe0_ctrl__DOT__u_trace_wb__DOT__rb_idx_w;
        CData/*4:0*/ u_pipe0_ctrl__DOT__u_trace_wb__DOT__rd_idx_w;
        CData/*0:0*/ u_pipe1_ctrl__DOT__clk_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__rst_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__issue_valid_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__issue_accept_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__issue_stall_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__issue_lsu_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__issue_csr_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__issue_div_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__issue_mul_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__issue_branch_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__issue_rd_valid_i;
        CData/*4:0*/ u_pipe1_ctrl__DOT__issue_rd_i;
        CData/*5:0*/ u_pipe1_ctrl__DOT__issue_exception_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__take_interrupt_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__issue_branch_taken_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__csr_result_write_e1_i;
        CData/*5:0*/ u_pipe1_ctrl__DOT__csr_result_exception_e1_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__load_e1_o;
        CData/*0:0*/ u_pipe1_ctrl__DOT__store_e1_o;
        CData/*0:0*/ u_pipe1_ctrl__DOT__mul_e1_o;
        CData/*0:0*/ u_pipe1_ctrl__DOT__branch_e1_o;
        CData/*4:0*/ u_pipe1_ctrl__DOT__rd_e1_o;
    };
    struct {
        CData/*0:0*/ u_pipe1_ctrl__DOT__mem_complete_i;
        CData/*5:0*/ u_pipe1_ctrl__DOT__mem_exception_e2_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__load_e2_o;
        CData/*0:0*/ u_pipe1_ctrl__DOT__mul_e2_o;
        CData/*4:0*/ u_pipe1_ctrl__DOT__rd_e2_o;
        CData/*0:0*/ u_pipe1_ctrl__DOT__div_complete_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__valid_wb_o;
        CData/*0:0*/ u_pipe1_ctrl__DOT__csr_wb_o;
        CData/*4:0*/ u_pipe1_ctrl__DOT__rd_wb_o;
        CData/*5:0*/ u_pipe1_ctrl__DOT__exception_wb_o;
        CData/*0:0*/ u_pipe1_ctrl__DOT__csr_write_wb_o;
        CData/*0:0*/ u_pipe1_ctrl__DOT__stall_o;
        CData/*0:0*/ u_pipe1_ctrl__DOT__squash_e1_e2_o;
        CData/*0:0*/ u_pipe1_ctrl__DOT__squash_e1_e2_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__squash_wb_i;
        CData/*0:0*/ u_pipe1_ctrl__DOT__squash_e1_e2_w;
        CData/*0:0*/ u_pipe1_ctrl__DOT__branch_misaligned_w;
        CData/*0:0*/ u_pipe1_ctrl__DOT__valid_e1_q;
        CData/*5:0*/ u_pipe1_ctrl__DOT__exception_e1_q;
        CData/*0:0*/ u_pipe1_ctrl__DOT__alu_e1_w;
        CData/*0:0*/ u_pipe1_ctrl__DOT__csr_e1_w;
        CData/*0:0*/ u_pipe1_ctrl__DOT__div_e1_w;
        CData/*0:0*/ u_pipe1_ctrl__DOT__valid_e2_q;
        CData/*0:0*/ u_pipe1_ctrl__DOT__csr_wr_e2_q;
        CData/*5:0*/ u_pipe1_ctrl__DOT__exception_e2_q;
        CData/*0:0*/ u_pipe1_ctrl__DOT__valid_e2_w;
        CData/*0:0*/ u_pipe1_ctrl__DOT__load_store_e2_w;
        CData/*5:0*/ u_pipe1_ctrl__DOT__exception_e2_r;
        CData/*0:0*/ u_pipe1_ctrl__DOT__squash_e1_e2_q;
        CData/*0:0*/ u_pipe1_ctrl__DOT__valid_wb_q;
        CData/*0:0*/ u_pipe1_ctrl__DOT__csr_wr_wb_q;
        CData/*5:0*/ u_pipe1_ctrl__DOT__exception_wb_q;
        CData/*0:0*/ u_pipe1_ctrl__DOT__complete_wb_w;
        CData/*0:0*/ u_pipe1_ctrl__DOT__u_trace_d__DOT__valid_i;
        CData/*4:0*/ u_pipe1_ctrl__DOT__u_trace_d__DOT__ra_idx_w;
        CData/*4:0*/ u_pipe1_ctrl__DOT__u_trace_d__DOT__rb_idx_w;
        CData/*4:0*/ u_pipe1_ctrl__DOT__u_trace_d__DOT__rd_idx_w;
        CData/*0:0*/ u_pipe1_ctrl__DOT__u_trace_wb__DOT__valid_i;
        CData/*4:0*/ u_pipe1_ctrl__DOT__u_trace_wb__DOT__ra_idx_w;
        CData/*4:0*/ u_pipe1_ctrl__DOT__u_trace_wb__DOT__rb_idx_w;
        CData/*4:0*/ u_pipe1_ctrl__DOT__u_trace_wb__DOT__rd_idx_w;
        CData/*0:0*/ u_pipe0_dec0_verif__DOT__valid_i;
        CData/*4:0*/ u_pipe0_dec0_verif__DOT__ra_idx_w;
        CData/*4:0*/ u_pipe0_dec0_verif__DOT__rb_idx_w;
        CData/*4:0*/ u_pipe0_dec0_verif__DOT__rd_idx_w;
        CData/*0:0*/ u_pipe0_dec1_verif__DOT__valid_i;
        CData/*4:0*/ u_pipe0_dec1_verif__DOT__ra_idx_w;
        CData/*4:0*/ u_pipe0_dec1_verif__DOT__rb_idx_w;
        CData/*4:0*/ u_pipe0_dec1_verif__DOT__rd_idx_w;
        VL_OUT16(csr_writeback_waddr_o,11,0);
        SData/*11:0*/ u_pipe0_ctrl__DOT__csr_waddr_wb_o;
        SData/*9:0*/ u_pipe0_ctrl__DOT__ctrl_e1_q;
        SData/*9:0*/ u_pipe0_ctrl__DOT__ctrl_e2_q;
        SData/*9:0*/ u_pipe0_ctrl__DOT__ctrl_wb_q;
        SData/*11:0*/ u_pipe1_ctrl__DOT__csr_waddr_wb_o;
        SData/*9:0*/ u_pipe1_ctrl__DOT__ctrl_e1_q;
        SData/*9:0*/ u_pipe1_ctrl__DOT__ctrl_e2_q;
        SData/*9:0*/ u_pipe1_ctrl__DOT__ctrl_wb_q;
        VL_IN(fetch0_instr_i,31,0);
        VL_IN(fetch0_pc_i,31,0);
        VL_IN(fetch1_instr_i,31,0);
        VL_IN(fetch1_pc_i,31,0);
        VL_IN(branch_exec0_source_i,31,0);
        VL_IN(branch_exec0_pc_i,31,0);
    };
    struct {
        VL_IN(branch_d_exec0_pc_i,31,0);
        VL_IN(branch_exec1_source_i,31,0);
        VL_IN(branch_exec1_pc_i,31,0);
        VL_IN(branch_d_exec1_pc_i,31,0);
        VL_IN(branch_csr_pc_i,31,0);
        VL_IN(writeback_exec0_value_i,31,0);
        VL_IN(writeback_exec1_value_i,31,0);
        VL_IN(writeback_mem_value_i,31,0);
        VL_IN(writeback_mul_value_i,31,0);
        VL_IN(writeback_div_value_i,31,0);
        VL_IN(csr_result_e1_value_i,31,0);
        VL_IN(csr_result_e1_wdata_i,31,0);
        VL_OUT(branch_pc_o,31,0);
        VL_OUT(branch_info_source_o,31,0);
        VL_OUT(branch_info_pc_o,31,0);
        VL_OUT(opcode0_opcode_o,31,0);
        VL_OUT(opcode0_pc_o,31,0);
        VL_OUT(opcode0_ra_operand_o,31,0);
        VL_OUT(opcode0_rb_operand_o,31,0);
        VL_OUT(opcode1_opcode_o,31,0);
        VL_OUT(opcode1_pc_o,31,0);
        VL_OUT(opcode1_ra_operand_o,31,0);
        VL_OUT(opcode1_rb_operand_o,31,0);
        VL_OUT(lsu_opcode_opcode_o,31,0);
        VL_OUT(lsu_opcode_pc_o,31,0);
        VL_OUT(lsu_opcode_ra_operand_o,31,0);
        VL_OUT(lsu_opcode_rb_operand_o,31,0);
        VL_OUT(mul_opcode_opcode_o,31,0);
        VL_OUT(mul_opcode_pc_o,31,0);
        VL_OUT(mul_opcode_ra_operand_o,31,0);
        VL_OUT(mul_opcode_rb_operand_o,31,0);
        VL_OUT(csr_opcode_opcode_o,31,0);
        VL_OUT(csr_opcode_pc_o,31,0);
        VL_OUT(csr_opcode_ra_operand_o,31,0);
        VL_OUT(csr_opcode_rb_operand_o,31,0);
        VL_OUT(csr_writeback_wdata_o,31,0);
        VL_OUT(csr_writeback_exception_pc_o,31,0);
        VL_OUT(csr_writeback_exception_addr_o,31,0);
        IData/*31:0*/ pc_x_q;
        IData/*31:0*/ opcode_a_r;
        IData/*31:0*/ opcode_b_r;
        IData/*31:0*/ opcode_a_pc_r;
        IData/*31:0*/ opcode_b_pc_r;
        IData/*31:0*/ pipe0_pc_e1_w;
        IData/*31:0*/ pipe0_opcode_e1_w;
        IData/*31:0*/ pipe0_operand_ra_e1_w;
        IData/*31:0*/ pipe0_operand_rb_e1_w;
        IData/*31:0*/ pipe0_result_e2_w;
        IData/*31:0*/ pipe0_result_wb_w;
        IData/*31:0*/ pipe0_pc_wb_w;
        IData/*31:0*/ pipe0_opc_wb_w;
        IData/*31:0*/ pipe0_ra_val_wb_w;
        IData/*31:0*/ pipe0_rb_val_wb_w;
        IData/*31:0*/ pipe1_pc_e1_w;
        IData/*31:0*/ pipe1_opcode_e1_w;
        IData/*31:0*/ pipe1_operand_ra_e1_w;
        IData/*31:0*/ pipe1_operand_rb_e1_w;
        IData/*31:0*/ pipe1_result_e2_w;
        IData/*31:0*/ pipe1_result_wb_w;
        IData/*31:0*/ pipe1_pc_wb_w;
        IData/*31:0*/ pipe1_opc_wb_w;
        IData/*31:0*/ pipe1_ra_val_wb_w;
        IData/*31:0*/ pipe1_rb_val_wb_w;
        IData/*31:0*/ scoreboard_r;
    };
    struct {
        IData/*31:0*/ issue_a_ra_value_w;
        IData/*31:0*/ issue_a_rb_value_w;
        IData/*31:0*/ issue_b_ra_value_w;
        IData/*31:0*/ issue_b_rb_value_w;
        IData/*31:0*/ issue_a_ra_value_r;
        IData/*31:0*/ issue_a_rb_value_r;
        IData/*31:0*/ issue_b_ra_value_r;
        IData/*31:0*/ issue_b_rb_value_r;
        IData/*31:0*/ u_pipe0_ctrl__DOT__issue_branch_target_i;
        IData/*31:0*/ u_pipe0_ctrl__DOT__issue_pc_i;
        IData/*31:0*/ u_pipe0_ctrl__DOT__issue_opcode_i;
        IData/*31:0*/ u_pipe0_ctrl__DOT__issue_operand_ra_i;
        IData/*31:0*/ u_pipe0_ctrl__DOT__issue_operand_rb_i;
        IData/*31:0*/ u_pipe0_ctrl__DOT__alu_result_e1_i;
        IData/*31:0*/ u_pipe0_ctrl__DOT__csr_result_value_e1_i;
        IData/*31:0*/ u_pipe0_ctrl__DOT__csr_result_wdata_e1_i;
        IData/*31:0*/ u_pipe0_ctrl__DOT__pc_e1_o;
        IData/*31:0*/ u_pipe0_ctrl__DOT__opcode_e1_o;
        IData/*31:0*/ u_pipe0_ctrl__DOT__operand_ra_e1_o;
        IData/*31:0*/ u_pipe0_ctrl__DOT__operand_rb_e1_o;
        IData/*31:0*/ u_pipe0_ctrl__DOT__mem_result_e2_i;
        IData/*31:0*/ u_pipe0_ctrl__DOT__mul_result_e2_i;
        IData/*31:0*/ u_pipe0_ctrl__DOT__result_e2_o;
        IData/*31:0*/ u_pipe0_ctrl__DOT__div_result_i;
        IData/*31:0*/ u_pipe0_ctrl__DOT__result_wb_o;
        IData/*31:0*/ u_pipe0_ctrl__DOT__pc_wb_o;
        IData/*31:0*/ u_pipe0_ctrl__DOT__opcode_wb_o;
        IData/*31:0*/ u_pipe0_ctrl__DOT__operand_ra_wb_o;
        IData/*31:0*/ u_pipe0_ctrl__DOT__operand_rb_wb_o;
        IData/*31:0*/ u_pipe0_ctrl__DOT__csr_wdata_wb_o;
        IData/*31:0*/ u_pipe0_ctrl__DOT__pc_e1_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__npc_e1_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__opcode_e1_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__operand_ra_e1_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__operand_rb_e1_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__csr_wdata_e2_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__result_e2_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__pc_e2_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__npc_e2_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__opcode_e2_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__operand_ra_e2_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__operand_rb_e2_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__result_e2_r;
        IData/*31:0*/ u_pipe0_ctrl__DOT__csr_wdata_wb_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__result_wb_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__pc_wb_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__npc_wb_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__opcode_wb_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__operand_ra_wb_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__operand_rb_wb_q;
        IData/*31:0*/ u_pipe0_ctrl__DOT__u_trace_d__DOT__pc_i;
        IData/*31:0*/ u_pipe0_ctrl__DOT__u_trace_d__DOT__opcode_i;
        VlWide<3>/*79:0*/ u_pipe0_ctrl__DOT__u_trace_d__DOT__dbg_inst_str;
        VlWide<3>/*79:0*/ u_pipe0_ctrl__DOT__u_trace_d__DOT__dbg_inst_ra;
        VlWide<3>/*79:0*/ u_pipe0_ctrl__DOT__u_trace_d__DOT__dbg_inst_rb;
        VlWide<3>/*79:0*/ u_pipe0_ctrl__DOT__u_trace_d__DOT__dbg_inst_rd;
        IData/*31:0*/ u_pipe0_ctrl__DOT__u_trace_d__DOT__dbg_inst_imm;
        IData/*31:0*/ u_pipe0_ctrl__DOT__u_trace_d__DOT__dbg_inst_pc;
        IData/*31:0*/ u_pipe0_ctrl__DOT__u_trace_wb__DOT__pc_i;
        IData/*31:0*/ u_pipe0_ctrl__DOT__u_trace_wb__DOT__opcode_i;
        VlWide<3>/*79:0*/ u_pipe0_ctrl__DOT__u_trace_wb__DOT__dbg_inst_str;
        VlWide<3>/*79:0*/ u_pipe0_ctrl__DOT__u_trace_wb__DOT__dbg_inst_ra;
        VlWide<3>/*79:0*/ u_pipe0_ctrl__DOT__u_trace_wb__DOT__dbg_inst_rb;
        VlWide<3>/*79:0*/ u_pipe0_ctrl__DOT__u_trace_wb__DOT__dbg_inst_rd;
    };
    struct {
        IData/*31:0*/ u_pipe0_ctrl__DOT__u_trace_wb__DOT__dbg_inst_imm;
        IData/*31:0*/ u_pipe0_ctrl__DOT__u_trace_wb__DOT__dbg_inst_pc;
        VlWide<3>/*79:0*/ u_pipe0_ctrl__DOT__u_trace_wb__DOT____VdfgExtracted_h80d7e585__0;
        VlWide<3>/*79:0*/ u_pipe0_ctrl__DOT__u_trace_wb__DOT____VdfgExtracted_hef8b1dcb__0;
        VlWide<3>/*79:0*/ u_pipe0_ctrl__DOT__u_trace_wb__DOT____VdfgExtracted_h5dd7f615__0;
        IData/*31:0*/ u_pipe1_ctrl__DOT__issue_branch_target_i;
        IData/*31:0*/ u_pipe1_ctrl__DOT__issue_pc_i;
        IData/*31:0*/ u_pipe1_ctrl__DOT__issue_opcode_i;
        IData/*31:0*/ u_pipe1_ctrl__DOT__issue_operand_ra_i;
        IData/*31:0*/ u_pipe1_ctrl__DOT__issue_operand_rb_i;
        IData/*31:0*/ u_pipe1_ctrl__DOT__alu_result_e1_i;
        IData/*31:0*/ u_pipe1_ctrl__DOT__csr_result_value_e1_i;
        IData/*31:0*/ u_pipe1_ctrl__DOT__csr_result_wdata_e1_i;
        IData/*31:0*/ u_pipe1_ctrl__DOT__pc_e1_o;
        IData/*31:0*/ u_pipe1_ctrl__DOT__opcode_e1_o;
        IData/*31:0*/ u_pipe1_ctrl__DOT__operand_ra_e1_o;
        IData/*31:0*/ u_pipe1_ctrl__DOT__operand_rb_e1_o;
        IData/*31:0*/ u_pipe1_ctrl__DOT__mem_result_e2_i;
        IData/*31:0*/ u_pipe1_ctrl__DOT__mul_result_e2_i;
        IData/*31:0*/ u_pipe1_ctrl__DOT__result_e2_o;
        IData/*31:0*/ u_pipe1_ctrl__DOT__div_result_i;
        IData/*31:0*/ u_pipe1_ctrl__DOT__result_wb_o;
        IData/*31:0*/ u_pipe1_ctrl__DOT__pc_wb_o;
        IData/*31:0*/ u_pipe1_ctrl__DOT__opcode_wb_o;
        IData/*31:0*/ u_pipe1_ctrl__DOT__operand_ra_wb_o;
        IData/*31:0*/ u_pipe1_ctrl__DOT__operand_rb_wb_o;
        IData/*31:0*/ u_pipe1_ctrl__DOT__csr_wdata_wb_o;
        IData/*31:0*/ u_pipe1_ctrl__DOT__pc_e1_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__npc_e1_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__opcode_e1_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__operand_ra_e1_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__operand_rb_e1_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__csr_wdata_e2_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__result_e2_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__pc_e2_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__npc_e2_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__opcode_e2_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__operand_ra_e2_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__operand_rb_e2_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__result_e2_r;
        IData/*31:0*/ u_pipe1_ctrl__DOT__csr_wdata_wb_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__result_wb_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__pc_wb_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__npc_wb_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__opcode_wb_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__operand_ra_wb_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__operand_rb_wb_q;
        IData/*31:0*/ u_pipe1_ctrl__DOT__u_trace_d__DOT__pc_i;
        IData/*31:0*/ u_pipe1_ctrl__DOT__u_trace_d__DOT__opcode_i;
        VlWide<3>/*79:0*/ u_pipe1_ctrl__DOT__u_trace_d__DOT__dbg_inst_str;
        VlWide<3>/*79:0*/ u_pipe1_ctrl__DOT__u_trace_d__DOT__dbg_inst_ra;
        VlWide<3>/*79:0*/ u_pipe1_ctrl__DOT__u_trace_d__DOT__dbg_inst_rb;
        VlWide<3>/*79:0*/ u_pipe1_ctrl__DOT__u_trace_d__DOT__dbg_inst_rd;
        IData/*31:0*/ u_pipe1_ctrl__DOT__u_trace_d__DOT__dbg_inst_imm;
        IData/*31:0*/ u_pipe1_ctrl__DOT__u_trace_d__DOT__dbg_inst_pc;
        IData/*31:0*/ u_pipe1_ctrl__DOT__u_trace_wb__DOT__pc_i;
        IData/*31:0*/ u_pipe1_ctrl__DOT__u_trace_wb__DOT__opcode_i;
        VlWide<3>/*79:0*/ u_pipe1_ctrl__DOT__u_trace_wb__DOT__dbg_inst_str;
        VlWide<3>/*79:0*/ u_pipe1_ctrl__DOT__u_trace_wb__DOT__dbg_inst_ra;
        VlWide<3>/*79:0*/ u_pipe1_ctrl__DOT__u_trace_wb__DOT__dbg_inst_rb;
        VlWide<3>/*79:0*/ u_pipe1_ctrl__DOT__u_trace_wb__DOT__dbg_inst_rd;
        IData/*31:0*/ u_pipe1_ctrl__DOT__u_trace_wb__DOT__dbg_inst_imm;
        IData/*31:0*/ u_pipe1_ctrl__DOT__u_trace_wb__DOT__dbg_inst_pc;
        VlWide<3>/*79:0*/ u_pipe1_ctrl__DOT__u_trace_wb__DOT____VdfgExtracted_h80d7e585__0;
    };
    struct {
        VlWide<3>/*79:0*/ u_pipe1_ctrl__DOT__u_trace_wb__DOT____VdfgExtracted_hef8b1dcb__0;
        VlWide<3>/*79:0*/ u_pipe1_ctrl__DOT__u_trace_wb__DOT____VdfgExtracted_h5dd7f615__0;
        IData/*31:0*/ u_pipe0_dec0_verif__DOT__pc_i;
        IData/*31:0*/ u_pipe0_dec0_verif__DOT__opcode_i;
        VlWide<3>/*79:0*/ u_pipe0_dec0_verif__DOT__dbg_inst_str;
        VlWide<3>/*79:0*/ u_pipe0_dec0_verif__DOT__dbg_inst_ra;
        VlWide<3>/*79:0*/ u_pipe0_dec0_verif__DOT__dbg_inst_rb;
        VlWide<3>/*79:0*/ u_pipe0_dec0_verif__DOT__dbg_inst_rd;
        IData/*31:0*/ u_pipe0_dec0_verif__DOT__dbg_inst_imm;
        IData/*31:0*/ u_pipe0_dec0_verif__DOT__dbg_inst_pc;
        VlWide<3>/*79:0*/ u_pipe0_dec0_verif__DOT____VdfgExtracted_h80d7e585__0;
        VlWide<3>/*79:0*/ u_pipe0_dec0_verif__DOT____VdfgExtracted_hef8b1dcb__0;
        VlWide<3>/*79:0*/ u_pipe0_dec0_verif__DOT____VdfgExtracted_h5dd7f615__0;
        IData/*31:0*/ u_pipe0_dec1_verif__DOT__pc_i;
        IData/*31:0*/ u_pipe0_dec1_verif__DOT__opcode_i;
        VlWide<3>/*79:0*/ u_pipe0_dec1_verif__DOT__dbg_inst_str;
        VlWide<3>/*79:0*/ u_pipe0_dec1_verif__DOT__dbg_inst_ra;
        VlWide<3>/*79:0*/ u_pipe0_dec1_verif__DOT__dbg_inst_rb;
        VlWide<3>/*79:0*/ u_pipe0_dec1_verif__DOT__dbg_inst_rd;
        IData/*31:0*/ u_pipe0_dec1_verif__DOT__dbg_inst_imm;
        IData/*31:0*/ u_pipe0_dec1_verif__DOT__dbg_inst_pc;
        VlWide<3>/*79:0*/ u_pipe0_dec1_verif__DOT____VdfgExtracted_h80d7e585__0;
        VlWide<3>/*79:0*/ u_pipe0_dec1_verif__DOT____VdfgExtracted_hef8b1dcb__0;
        VlWide<3>/*79:0*/ u_pipe0_dec1_verif__DOT____VdfgExtracted_h5dd7f615__0;
    };

    // INTERNAL VARIABLES
    Vbiriscv_mem_top__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr IData/*31:0*/ SUPPORT_MULDIV = 1U;
    static constexpr IData/*31:0*/ SUPPORT_DUAL_ISSUE = 1U;
    static constexpr IData/*31:0*/ SUPPORT_LOAD_BYPASS = 1U;
    static constexpr IData/*31:0*/ SUPPORT_MUL_BYPASS = 1U;
    static constexpr IData/*31:0*/ SUPPORT_REGFILE_XILINX = 0U;
    static constexpr IData/*31:0*/ u_pipe0_ctrl__DOT__SUPPORT_LOAD_BYPASS = 1U;
    static constexpr IData/*31:0*/ u_pipe0_ctrl__DOT__SUPPORT_MUL_BYPASS = 1U;
    static constexpr IData/*31:0*/ u_pipe1_ctrl__DOT__SUPPORT_LOAD_BYPASS = 1U;
    static constexpr IData/*31:0*/ u_pipe1_ctrl__DOT__SUPPORT_MUL_BYPASS = 1U;

    // CONSTRUCTORS
    Vbiriscv_mem_top_biriscv_issue(Vbiriscv_mem_top__Syms* symsp, const char* v__name);
    ~Vbiriscv_mem_top_biriscv_issue();
    VL_UNCOPYABLE(Vbiriscv_mem_top_biriscv_issue);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
    uint32_t complete_exception();
    uint32_t complete_opcode0();
    uint32_t complete_opcode1();
    uint32_t complete_pc0();
    uint32_t complete_pc1();
    uint32_t complete_ra0();
    uint32_t complete_ra1();
    uint32_t complete_ra_val0();
    uint32_t complete_ra_val1();
    uint32_t complete_rb0();
    uint32_t complete_rb1();
    uint32_t complete_rb_val0();
    uint32_t complete_rb_val1();
    uint32_t complete_rd0();
    uint32_t complete_rd1();
    uint32_t complete_rd_val0();
    uint32_t complete_rd_val1();
    bool complete_valid0();
    bool complete_valid1();
};


#endif  // guard
